### ISSUE TITLE
command failed with exit code 1

### ISSUE THREAD

**Issue by misterfonka** [MercuryWorkshop/RecoMod#10]
Notes - Running on a kali linux live usb (only usb i had around), i did recomod on kali before and it worked just fine, but it isn't working now. I tried reinstall RecoMod and the recovery image but nothing works

Terminal output:

sudo ./recomod.sh -i ~/Downloads/chromeos_15117.111.0_octopus_recovery_stable-channel_mp-v31.bin.zip --halcyon --rw_legacy 

Info: Downloading clamide into lib/
Info: Downloading pv into lib/
Info: Downloading latest rw_legacy payloads into lib/rwl
Info: Creating loopback device
losetup: /home/kali/Downloads/chromeos_15117.111.0_octopus_recovery_stable-channel_mp-v31.bin.zip: Warning: file does not fit into a 512-byte sector; the end of the file will be ignored.
"configure_binaries": $@ > /dev/null 2>&1 command failed with exit code 1. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod

**Comment by misterfonka** [comment]
ok so this is weird, i got the same exact error when I tried to do this on a virtual machine of linux mint? what do i do?

**Comment by CoolElectronics** [comment]
unzip the zip... you run it on the .bin

**Comment by misterfonka** [comment]
omg im actually dumb SORRY
