### ISSUE TITLE
[E-Halcyon] error while runnig sudo ./recomod.sh -i /path/to/recovery/image.bin --halcyon --rw_legacy

### ISSUE THREAD

**Issue by jjjaaail** [MercuryWorkshop/RecoMod#16]
execution environment: Linux on Chrome OS
version 107 recovery image for my bord:
https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_15117.111.0_octopus_recovery_stable-channel_mp-v31.bin.zip
![Screenshot 2023-08-16 21 53 44](https://github.com/MercuryWorkshop/RecoMod/assets/142410899/a446d395-31ab-4280-af21-e851f3199f5b)
A bug occurred while executing a shell script. I checked the losetup command in the area where the problem was occurring and the command did not exist. Attempting to install it was impossible.

**Comment by CheeseisYummy1234** [comment]
The same has happened to me, I tried building it in a remote desktop in github codespace. That might be the problem for me, were you running it in a remote desktop?

**Comment by kxtzownsu** [comment]
.... are your fr?

**Comment by CheeseisYummy1234** [comment]
I know, it was stupid to try to build it on a remote desktop using github codespace, didn't work either, oh well

**Comment by hard-shutdown** [comment]
that's not the issue, check the command you're running
