### ISSUE TITLE
Out of Space

### ISSUE THREAD

**Issue by Wildtick** [MercuryWorkshop/RecoMod#18]
After E-Halcyon writes whats on my usb to my chromebook the 2nd step starts and then shortly after stops after saying "No space left on /dev/m (random shit i don't know) 0" Any fix?

**Comment by TheMemeSniper** [comment]
get a bigger disk

**Comment by Wildtick** [comment]
i have 32gb of space on my chromebook tho. Do i get a bigger usb or no?

**Comment by TheMemeSniper** [comment]
whatever disk you're running the script from has no more space
