### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by scopedflux** [MercuryWorkshop/RecoMod#2]
./recomod.sh: line 79: curl: command not found
"suppress sysctl -w fs.protected_regular=0": curl -sL https://github.com/CoolElectronics/clamide/releases/latest/download/clamide -o "${SCRIPT_DIR}/lib/clamide" command failed with exit code 127. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod

**Comment by CoolElectronics** [comment]
... install curl

**Comment by scopedflux** [comment]
thx

**Comment by ninjaWolf8724** [comment]
:skull:
