### ISSUE TITLE
Pass Path to Recovery Image

### ISSUE THREAD

**Issue by thed3x7er500** [MercuryWorkshop/RecoMod#22]
BEFORE U SAY IM USEING WSL, I TRIED ON VM AND CHROMEOS AND STILL SAME ERROR

everytime i run this command it just says its not a real file, i tried 3 times, once on WSL, once on VM, and once on ChromeOS but same error all 3 times, i know im doing something wrong. Please help me if you can :/ 

![image](https://github.com/MercuryWorkshop/RecoMod/assets/110211674/87172244-f60d-4235-863f-cba82f834379)

**Comment by TheMemeSniper** [comment]
why are you using a windows path on linux

**Comment by thed3x7er500** [comment]
idk

**Comment by thed3x7er500** [comment]
leme try in linux

**Comment by thed3x7er500** [comment]
![image](https://github.com/MercuryWorkshop/RecoMod/assets/110211674/6d0cbb74-9a1e-44f4-9bd0-ddcf2be11b46)

**Comment by TheMemeSniper** [comment]
you forgot to put the / before `home/...`

**Comment by thed3x7er500** [comment]
> you forgot to put the / before `home/...`

no i had real time protection on, im stupid
