### ISSUE TITLE
"configure_binaries": loopdev=$(losetup -f) command failed with exit code 1

### ISSUE THREAD

**Issue by hongglong** [MercuryWorkshop/RecoMod#25]
Info: Creating loopback device
losetup: cannot find an unused loop device: No such device
"configure_binaries": loopdev=$(losetup -f) command failed with exit code 1. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod

**Comment by CoolElectronics** [comment]
you are using wsl or an unsupported linux distribution
use a supported device

**Comment by CoolElectronics** [comment]
you can't use crostini either

**Comment by hongglong** [comment]
would linux mint work?

**Comment by CoolElectronics** [comment]
yes

**Comment by hongglong** [comment]
i tried it on a debian vm and it still says that

**Comment by hongglong** [comment]
im gonna try ubuntu

**Comment by hongglong** [comment]
it worked with arch
