### ISSUE TITLE
Continues to enroll after boot

### ISSUE THREAD

**Issue by H644b** [MercuryWorkshop/RecoMod#27]
as soon as I boot it up it just re-enrolls again

**Comment by CoolElectronics** [comment]
user error

**Comment by Wildtick** [comment]
@H644b how did you turn off verify on root and disable flags...

**Comment by H644b** [comment]
I did it with my sh1mmer usb

**Comment by STANTHECHEESEMAN** [comment]
> I Fixed it, had to not just click un-enroll on Sh1mmer, had to turn off verify on root and disable flags. I had to then on E-Halcyon use recovery and then boot.

@H644b oh so thats what i did wrong
