### ISSUE TITLE
command failed with exit code 1

### ISSUE THREAD

**Issue by PluckybandYT** [MercuryWorkshop/RecoMod#28]
I never really liked doing this setup with my chromebook and used a linux pc instead but I tried doing it today and i kept getting the same error. My guess is that I got the file location incorrect since that's what I could never figure out. If there's no solution then I'll do it at home instead.

Thanks

![Screenshot 2023-09-15 11 06 55 AM](https://github.com/MercuryWorkshop/RecoMod/assets/85187681/c94b7a56-4d30-40ef-8e44-019b00efa347)

**Comment by CoolElectronics** [comment]
you can't use crostini
