### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by cistuff** [MercuryWorkshop/RecoMod#29]
flags: WARN: getpot: unrecognized option '--halcyon'
-i '/home/user/Downloads/image.bin' --rw_legacy --
flags: FATAL unable to parse provided options with getopt.

Below that there was red text telling me to report the bug to here.

**Comment by CoolElectronics** [comment]
what command did you type in

**Comment by c0des1ay3r** [comment]
no, it is supposed to be --halcyon, the [no] just means that it can be --nohalcyon instead.

**Comment by zek-c** [comment]
i'm gonna touch you

**Comment by c0des1ay3r** [comment]
what???
