### ISSUE TITLE
"Your system is repairing itself" after pressing "Boot halcyon semi-tethered""

### ISSUE THREAD

**Issue by ballinn9** [MercuryWorkshop/RecoMod#3]
My system has not booted into an unenrolled ChromeOS environment after doing every step correctly. However, it has instead gone into a prompt that lasts for several minutes without change. The prompt states that the "system is repairing itself" every time I try to boot into the environment.

**Comment by CoolElectronics** [comment]
fixed

**Comment by Straxic** [comment]
i keep getting this when i try to use the recomod and e-halcyon
Info: Downloading clamide into lib/
Info: Downloading pv into lib/
"suppress sysctlw fs.protected regular=0": curl -sl. https://github.com/mosajjal/binary-tools/raw/master/x64/pv -o lib/pv command failed with exit code 23. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod

**Comment by GameBoyYeet** [comment]
report it as a seperate issue
