### ISSUE TITLE
 E-mode doesn't activate

### ISSUE THREAD

**Issue by CoolRacoonMan** [MercuryWorkshop/RecoMod#30]
I've tried lots of times and nothing I try works there is no 5-minute wait I've tried spamming on the black screen before the recovery screen I've tried spamming a bit during the recovery screen, and I've tried spamming the whole time nothing has worked. I don't know what to try anymore is there a solution I'm missing?

**Comment by CoolElectronics** [comment]
user error

**Comment by ownrcoding** [comment]
Spam E on the recovery screen for ~20 seconds until it shows "Enhanced disk deletion in progress".
