### ISSUE TITLE
Getting an error doing this recomod

### ISSUE THREAD

**Issue by pxchey** [MercuryWorkshop/RecoMod#37]
test@Tests-iMac ~ % cd RecoMod
test@Tests-iMac RecoMod % chmod +x recomod.sh
test@Tests-iMac RecoMod % ./recomod.sh -i /users/test/downloads/octopus.bin
flags:ERROR short flag required for (disable-verity) on this platform
"trap 'echo -e "\"${last_command}\": "$BASH_COMMAND" command failed with exit code $?. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod"' EXIT": return ${flags_return} command failed with exit code 2. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod

**Comment by TheMemeSniper** [comment]
OSX isn't supported if iirc @CoolElectronics

**Comment by pxchey** [comment]
Now that would explain it... Any ideas on what I should do haha

**Comment by TheMemeSniper** [comment]
linux VM or straight up bare metal if you're up for the task

**Comment by CoolElectronics** [comment]
yup no mac too much effort to maintain
