### ISSUE TITLE
Can't force devmode on

### ISSUE THREAD

**Issue by minystreem56** [MercuryWorkshop/RecoMod#38]
I have tried unplugging my battery and trying it but it just says that it failed to disable software WR protect. Downgraded from 117 to 107 and I'm unenrolled.

**Comment by zek-c** [comment]
it was a firmware update i believe that patched the battery method, or your chromebook is newer and wp cant be disabled by removing the battery. check for a WP screw, if you cant find one youll need solder or a suzyqable OR to be unenrolled to enable dev mode.
