### ISSUE TITLE
Can not build on Debian 12 VM

### ISSUE THREAD

**Issue by the-duck2010** [MercuryWorkshop/RecoMod#40]
Whenever I try to build using the command ```
recomod.sh -i octopus.bin -k my-kit
``` I get the error ```"suppress which sysctl": curl -sL http://GitHub.com/mosajjal/binary-tools/raw/master/x64/pv -o lib/pv command failed with exit code 23
```

**Comment by CoolElectronics** [comment]
install curl

**Comment by the-duck2010** [comment]
Curl is already installed.
