### ISSUE TITLE
Ubuntu E-halycon not working with RecoMod.

### ISSUE THREAD

**Issue by PeapGit** [MercuryWorkshop/RecoMod#41]
I tried using E-Halycon. This is what I got. I have all the binaries and am on Ubuntu. Warning: file does not fit into a 512-byte sector; the end of the file will be ignored.
"configure_binaries": $@ > /dev/null 2>&1 command failed with exit code 1. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod

**Comment by CoolElectronics** [comment]
corrupted recovery image, or forgot to unzip
