### ISSUE TITLE
Nothing Saves

### ISSUE THREAD

**Issue by openexclusiveegg** [MercuryWorkshop/RecoMod#43]
When i download apps on the play store and turn off my computer then boot it back up none of my apps are there anymore so I have to reinstall them again

**Comment by pisanvs** [comment]
Did you manage to fix this? I'm having the same issue.

**Comment by c0des1ay3r** [comment]
@pisanvs E-Halcyon has no persistence, so nothing saves, not even apps.

**Comment by pisanvs** [comment]
Oh, I didn't catch that in the docs... Is there a way to boot with the /home directory from the USB drive, or is ChromeOS too restricted for that?

**Comment by c0des1ay3r** [comment]
I may be wrong, but that sounds like something you'd have to make a modified init script for. I have no clue about how you would go about that, but I wish you luck on that. Maybe this might be a good starting point: [How do I use OverlayFS?](https://askubuntu.com/questions/109413/how-do-i-use-overlayfs)

**Comment by amogus-technologies** [comment]
https://fog.gay/#FAQ

> Unfixable restriction of cryptohome. See the [writeup](https://coolelectronics.me/blog/breaking-cros-5) for more information
