### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Endergod150** [MercuryWorkshop/RecoMod#46]
`losetup: dedede.bin: failed to set up loop device: Device or resource busy`

`"configure_binaries": losetup -P "$loopdev" "$bin" command failed with exit code 1.`

The rest is talking about reporting it here.

**Comment by Endergod150** [comment]
I looked at the debug and it was trying to run `losetup -P /dev/loop9 dedede.bin` when that happened.

**Comment by velzie** [comment]
idk reboot or something it's either not fully downloaded or open somewhere
