### ISSUE TITLE
"an unexpected error has occured"

### ISSUE THREAD

**Issue by RintaDev5792** [MercuryWorkshop/RecoMod#50]
I installed halcyon and did everything, and it worked great! So I shut off my Chromebook. I booted it up, it worked great again! Now I am trying to boot it, I get to the point where I spam e, and it says "an unexpected error has occured" and doesn't boot.

**Comment by Youraveragejoshhutcherson** [comment]
You're lucky to even get into the os i wasnt able to and when i did it was enrolled

**Comment by RintaDev5792** [comment]
Update: I fixed this by re-flashing a halcyon sd card, works fine now. Sorry!
