### ISSUE TITLE
OS verification 

### ISSUE THREAD

**Issue by scopedflux** [MercuryWorkshop/RecoMod#6]
![image](https://github.com/MercuryWorkshop/RecoMod/assets/126987297/cf115f10-4de2-4214-9873-bf763645d612)

**Comment by scopedflux** [comment]
Even if i spam e it still happens

**Comment by wwwwwwwbtqhwth** [comment]
what model of chromebook is it

**Comment by scopedflux** [comment]
hp chromebook 14a
grunt

**Comment by wwwwwwwbtqhwth** [comment]
Its because you didnt use sh1mmer before doingvthat

**Comment by wwwwwwwbtqhwth** [comment]
yeah like i said  you need to use sh1mmers unenroll option beofre doing that
