### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by STANTHECHEESEMAN** [MercuryWorkshop/RecoMod#63]
Everything was working fine while installing it onto the chromebook and stuff but when i booted it in semi-tethered it still enrolled after start up.

**Comment by TheMemeSniper** [comment]
what version is your chromebook on

**Comment by STANTHECHEESEMAN** [comment]
nvm i found something about it https://github.com/MercuryWorkshop/RecoMod/issues/27#issuecomment-1723097046

**Comment by STANTHECHEESEMAN** [comment]
https://github.com/MercuryWorkshop/RecoMod/issues/27#issuecomment-1723097046
