### ISSUE TITLE
":": curl -sL "${rwlegacy_source}${val}" -o "lib/rwl/$val" command failed with exit code 18. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod

### ISSUE THREAD

**Issue by Subbboys096** [MercuryWorkshop/RecoMod#7]
This bug appeared when I was trying to use the gefogger the command I used for the bug to appear was: 
sudo ./recomod.sh -i /storage/emulated/0/chromeos_15117.111.0_coral_recovery_stable-channel_mp-v19.bin --halcyon --rw_legacy
and the response it gave me was:
sysctl: permission denied on key 'fs.protected_regular'
Info: Downloading clamide into lib/
Info: Downloading pv into lib/
Info: Downloading latest rw_legacy payloads into lib/rwl
mkdir: cannot create directory ‘lib/rwl’: File exists
":": curl -sL "${rwlegacy_source}${val}" -o "lib/rwl/$val" command failed with exit code 18. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod

**Comment by wwwwwwwbtqhwth** [comment]
use sudo that should fix it

**Comment by CoolElectronics** [comment]
install curl

**Comment by Subbboys096** [comment]
> use sudo that should fix it

i did
