### ISSUE TITLE
"trap 'echo -e "\"${last_command}\": "$BASH_COMMAND" command failed with exit code $?. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod"' EXIT": return ${flags_return} command failed with exit code 2. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod

### ISSUE THREAD

**Issue by FlameUser706** [MercuryWorkshop/RecoMod#9]
```
"trap 'echo -e "\"${last_command}\": "$BASH_COMMAND" command failed with exit code $?. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod"' EXIT": return ${flags_return} command failed with exit code 2. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod
```

I do not know

**Comment by CoolElectronics** [comment]
run again with --debug appended, attach full log

**Comment by MuhammedowaisW** [comment]
I had this same problem, turns out I typed --halycon and not --halcyon in the last command

**Comment by some-du6e** [comment]
same
heres what outputted with debug
flags:ERROR short flag required for (disable-verity) on this platform
"trap 'echo -e "\"${last_command}\": "$BASH_COMMAND" command failed with exit code $?. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod"' EXIT": return ${flags_return} command failed with exit code 2. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod
I'm on macos 10.15 btw

**Comment by some-du6e** [comment]
> same heres what outputted with debug flags:ERROR short flag required for (disable-verity) on this platform "trap 'echo -e ""${last_command}": "$BASH_COMMAND" command failed with exit code $?. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod"' EXIT": return ${flags_return} command failed with exit code 2. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod I'm on macos 10.15 btw

also happens with just ./recomod
./recomod.sh 
flags:ERROR short flag required for (disable-verity) on this platform
"trap 'echo -e "\"${last_command}\": "$BASH_COMMAND" command failed with exit code $?. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod"' EXIT": return ${flags_return} command failed with exit code 2. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod

**Comment by CoolElectronics** [comment]
> same heres what outputted with debug flags:ERROR short flag required for (disable-verity) on this platform "trap 'echo -e ""${last_command}": "$BASH_COMMAND" command failed with exit code $?. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod"' EXIT": return ${flags_return} command failed with exit code 2. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/RecoMod I'm on macos 10.15 btw

gee i wonder why the linux bash script didn't work on mac os
please follow the instructions
